name: Chatbot CI/CD Pipeline

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.9'
            - name: Install Dependencies
              run: |
                pip install -r requirements.txt
            - name: Run Tests
              run: |
                pytest tests/


    docker-build:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            - name: Build and Push Docker Image
              run: |
                docker build -t chatbot-api:latest .
                docker tag chatbot-api:latest ${{ secrets.DOCKER_USERNAME }}/chatbot-api:latest
                docker push ${{ secrets.DOCKER_USERNAME }}/chatbot-api:latest
                
    deploy:
        needs: docker-build
        runs-on: ubuntu-latest
        steps:
            - name: Set up Kubectl
              uses: azure/setup-kubectl@v4
              with:
                version: 'latest'
            - name: Apply Kubernetes Deployment
              run: |
                kubectl apply -f deployment.yaml
                kubectl rollout restart deployment chatbot-deployment
    
    notification:
      needs: deploy
      runs-on: ubuntu-latest
      if: success()
      steps:
        - name: Send Telegram Notification
          uses: appleboy/telegram-action@v1.0.0
          with:
            token: ${{ secrets.TELEGRAM_TOKEN }}
            to: ${{ secrets.TELEGRAM_CHAT_ID }}
            message: "Deployment successful!"

        - name: Notify Slack
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_MESSAGE: "Chatbot API has been deployed successfully! 🚀"
      